version: '3.7'
services:
  postgres:
    image: postgres:11.5
    environment:
      POSTGRES_DB: tabung-sg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hunter2
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tabung-sg
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:hunter2@postgres:5432/tabung-sg
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  pgdata:
